#### 错误处理

Rust中错误分为了两大类

- 可恢复的
	- 比如文件未找到，可以重试什么的
- 不可恢复的
	- 访问了一个数组的末端等

Rust 中没有异常，使用 _Result<T, E>_ 用于处理可恢复的错误，还有 _panic!_ 宏 用于处理不可恢复的错误，所以需要立即终止程序

有两种方式可以造成 `painc` 一个是执行造成 `painc`的操作如

```rust
let v = vec![1, 2, 3];
v[10];
```

这里访问了超过数组结尾的内容了，程序就会 `painc`，或者可以显示的调用 _panic!_ 宏

```rust
panic!('程序出错了');
```

这个宏会输出错误信息，并展开清理栈数据，然后终止程序

可以在 `Cargo.toml` 配置文件中新增配置来设置  `painc`的展开或终止

```toml
[profile.release]
panic = 'abort'
```

> 当出现 panic 时，程序默认会开始 **展开**（_unwinding_），这意味着 Rust 会回溯栈并清理它遇到的每一个函数的数据，不过这个回溯并清理的过程有很多工作。另一种选择是直接 **终止**（_abort_），这会不清理数据就退出程序

还可以设置环境变量 `RUST_BACKTRACE` 来调整程序 `painc`时的打印信息详细程度

- **`0`：** 禁用 backtrace。在这种情况下，当程序发生 panic 时，通常只会打印 panic 的消息，而不会包含详细的调用栈信息。
- **`1`：** 启用 backtrace。当程序 panic 时，将打印包含简单调用栈信息的 backtrace。
- **`full`：** 启用完整 backtrace。当程序 panic 时，将打印包含完整调用栈信息的 backtrace。
例如

```shell
RUST_BACKTRACE=full cargo run
```

然而大部分时候错误并没有严重到需要程序完全停止，如打开一个文件，但是这个文件并不存在，这个时候可以考虑去创建这个文件，而不是直接停止程序

这个时候就可以考虑使用 _Result_ 了，它和  _Option_ 一样，也是一个枚举，它和他的成员也被 `prelude` 了

```rust
use std::fs::File;

fn main() {
	let file_result = File::open("test.txt");
	let file_data = match file_result {
		Ok(file) => file,
		Err(error) => panic("文件读取出错了 {:?}", error)
	};
}
```

这样就可以去处理读取文件成功，和失败了，当然这并没有达到我们预期的效果，只是区分了读取成功和失败的可能，而并不是所有的读取失败都是因为文件没有创建，所以还需要对错误更准确的区分一下

这里需要的是一个`io`的错误，所以从 `io` 中导入它

```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
	let file_result = File::open("test.txt");

	let file_data = match file_result {
		Ok(file) => file,
		Err(error) => match error.kind() {
			ErrorKind::NotFound => match File::create("test.txt") {
				Ok(fc) => fc,
				Err(e) => panic!("新建文件失败了 {:?}", e)
			},
			other_error => {
				panic!("其他错误 {:?}", other_error);
			}
		}
	};
}

```

`io::ErrorKind` 是标准库提供的枚举，对应 `io`操作不同的错误类型，_`kind`_ 方法用于获取`ErrorKind`枚举，然再去做处理

`match`确实很强大，但是有时候它有点昂长了，所以 `Result<T, E>` 类型给了一些辅助方法，例如 _unwrap_ 方法，如果 `Result`的值是 `Ok` 那就返回 `Ok`中的之后，否则调用 `panic!`

```rust
let file_data = File::open("test.txt").unwarp();
```

还有一个 _expect_ 方法，和 _unwrap_ 一样，但是可以自定义提示信息

```rust
let file_data = File::open("test.txt").expect("读取文件失败了");
```